name: Publish multi-arch Docker images

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "release/*"
      - "main/*"
      - "devel/*"
      - "feature/*"
      - "daily/*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base: ["trixie"]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Prepare for docker build
        id: prepare
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
          REF: ${{ github.ref }}
          DISTRO_ID: ${{ matrix.base }}
          GIT_BRANCH: version-0.24.13
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/mpd-compiler
        run: ./.github/scripts/prepare-docker-build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: |
            BASE_IMAGE=${{ steps.prepare.outputs.BASE_IMAGE }}
            USE_GIT_BRANCH=${{ steps.prepare.outputs.GIT_BRANCH }}
          platforms: ${{ steps.prepare.outputs.BUILD_PLATFORMS }}
          push: true
          tags: ${{ steps.prepare.outputs.RELEASE_TAGS }}
